# playbook.yml
---
- name: Run python script
  hosts: workers
  remote_user: stron
  become: yes

  tasks:
    - name: Update apt-get
      raw: sudo apt-get update
    - name: Install python3
      raw: sudo apt install -y python3-pip
    - name: Install prerequisites
      raw: pip3 install gensim
    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
      - { src: '~/repos/CloudApp/task.py', dest: '~/task.py' }
      - { src: '~/repos/CloudApp/pretrained.model', dest: '~/pretrained.model' }

    - name: Execute script
      raw: python3 ~/task.py

    - name: Fetch file
      fetch: src={{ item.src }} dest={{ item.dest }} flat=yes
      with_items:
      - { src: '~/output.txt', dest: '~/repos/CloudApp/{{ username }}/' }
