# playbook.yml
---
- name: Run python script
  hosts: workers
  remote_user: stron

  tasks:
    - name: Update apt-get
      become: yes
      raw: sudo apt-get update
      
    - name: Install python3
      become: yes
      raw: sudo apt install -y python3-pip
      
    - name: Install prerequisites
      become: yes
      raw: pip3 install gensim
      
    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
      - { src: '~/repos/CloudApp/task.py', dest: '~/sinonim/task.py' }
      - { src: '~/repos/CloudApp/pretrained.model', dest: '~/sinonim/pretrained.model' }

    - name: Execute script
      raw: python3 ~/sinonim/task.py

    - name: Fetch file
      fetch: src={{ item.src }} dest={{ item.dest }} flat=yes
      with_items:
      - { src: '~/sinonim/output.txt', dest: '~/repos/CloudApp/{{username}}/' }
