# playbook.yml
---
- name: Run python script
  hosts: workers
  remote_user: stron

  tasks:
    - name: Install prerequisites
      become: true
      apt:
        update_cache: yes
        pkg:
          python3-pip

    - pip: name=pip
      name: gensim==3.8.1

    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
      - { src: '~/repos/CloudApp/task.py', dest: '/task.py' }
      - { src: '~/repos/CloudApp/pretrained.model', dest: '/pretrained.model' }

    - name: Execute script
      command: /task.py

    - name: Fetch file
      fetch: src={{ item.src }} dest={{ item.dest }}
      with_items:
      - { src: '/output.txt', dest: '~/repos/CloudApp/output_{{ username }}.txt' }