# playbook.yml
---
- name: Run python script
  hosts: localhost

  tasks:
    - name: Install prerequisites
      become: yes
      raw: pip3 install gensim
      
    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
      - { src: '~/repos/CloudApp/task.py', dest: '~/repos/CloudApp/test/task.py' }
      - { src: '~/repos/CloudApp/pretrained.model', dest: '~/repos/CloudApp/test/pretrained.model' }

    - name: Execute script
      raw: python3 ~/repos/CloudApp/test/task.py

    - name: Fetch file
      fetch: src={{ item.src }} dest={{ item.dest }} flat=yes
      with_items:
      - { src: '~/repos/CloudApp/test/output.txt', dest: '~/repos/CloudApp/{username}' }
